### ISSUE TITLE
Process.Children() not implemented. 

### ISSUE THREAD

**Issue by Elleryia** [shirou/gopsutil#111]

**Comment by shirou** [comment]
Thanks. I will implement by using `pgrep -P 1`. Please be patient.

**Comment by Elleryia** [comment]
Also, just a heads up, pgrep -p <pid> only returns the children of that pid. If the children have pids then another pgrep is required. This function should only return the direct children of the given pid, but it may be worth having another that returns the process tree enumeration. For now it can be left to the user to walk the process tree.

**Comment by shirou** [comment]
I have merged #113 which can get `process.Children()`. It just returns children of the pid, so as you said, users need to invoke `Children()` recursively to get process tree. 

I think gopsutil itself should not provide such kind of *walking* function.

If you feel this issue is solved, could you please close this? Thank you!

**Comment by Elleryia** [comment]
Thank You!
