### ISSUE TITLE
[v3] Can not get mountinfo on android

### ISSUE THREAD

**Issue by shirou** [shirou/gopsutil#1159]
**Describe the bug**

#1133 changes getting mountinfo source from `/proc/self/mountinfo` to `/proc/1/mountinfo` in order to adapt container. However, from [this report](https://github.com/shirou/gopsutil/pull/1133#issuecomment-945991884) by @tmm1(thank you!) , Android can not read `/proc/1/mountinfo` because of `Permission denied`.

**Expected behavior**

success to get mountinfo.

**Environment (please complete the following information):**
 - [x] Linux: [paste contents of `/etc/os-release` and the result of `uname -a`]

android 

**Additional context**

Perhaps, we should add "fallback" to use `/proc/self/mountinfo` if error happened.

**Comment by Lomanic** [comment]
#1133 broke more than just Android apps, but also apps running as unprivileged users on systems with procfs mounted with `hidepid=2`, see #1212.

**Comment by cbos** [comment]
@shirou 

We face the same issue with Telegraf, see influxdata/telegraf#10357

We applied the CIS Hardening rules by running https://github.com/dev-sec/ansible-collection-hardening
Due to that hidepid is now applied. Since that moment the disk info about disk usage is not available anymore.
hidepid is a common security measure, see https://linux-audit.com/linux-system-hardening-adding-hidepid-to-proc/ for more info.

In the troubleshouting section of the disk plugin (https://github.com/influxdata/telegraf/tree/master/plugins/inputs/disk#troubleshooting) there is described to test this:
sudo -u telegraf cat /proc/self/mounts and that works fine.

So using /proc/self instead of /proc/1 would solve the problem.

As this project is used as upstream project, this block some functionality of Telegraf as well.
Hopefully it can be fixed soon.

**Comment by shirou** [comment]
#1270 created. Could you check by using that PR?

**Comment by cbos** [comment]
@shirou 
Thanks for fixing this. I quickly checked the code changes and that looks good to me as far as I can see.

@powersj 
What would be quick way I can validate this with telegraf?

**Comment by powersj** [comment]
I ran:

```
GOPROXY=direct go get -u github.com/shirou/gopsutil/v3@feature/disk_add_fallback_to_self_mountinfo
```

Which upgraded the gopsutil dependency to the branch with the fix. I have put up a [PR here](https://github.com/influxdata/telegraf/pull/10785), which should have some artifacts attached to it shortly that you can then try out.

**Comment by cbos** [comment]
@shirou @powersj 
I tested the new version available in the PR, and that solved the problem. I can read the data again.

**Comment by shirou** [comment]
#1270 has been merged. Thank you for confirming!

**Comment by cbos** [comment]
@shirou 
Thanks for fixing!
When do you expect a new release is available with this fix included?

**Comment by Lomanic** [comment]
gopsutil releases are monthly @cbos https://github.com/shirou/gopsutil#tag-semantics
