### ISSUE TITLE
binary.go duplicated in disk & process imports

### ISSUE THREAD

**Issue by rburchell** [shirou/gopsutil#147]
I noticed there's a binary.go file that seems to be in both the disk and process imports. Perhaps it should be moved to common? Although, I'm also not completely sure it's used at least in the disk case.

**Comment by shirou** [comment]
`binary.go` is a copy of `encoding/binary/binary.go`. But add `reflect.Ptr` to `sizeof`. I have to add it to get size of Ptr in order to parse struct. When golang add reflect.Ptr to `sizeof`, I want to delete my binary.go file. So the duplication is just temporary. 

(But golang seems not to add Ptr, so I am thinking about it's time to move under common...)

**Comment by shirou** [comment]
Sine 0af91ba32b4d7cc3a709e75575374b85e66005ad, `binary.go` has been moved to `internal/common`. Thank you for suggestion!
