### ISSUE TITLE
Implement run and block queue

### ISSUE THREAD

**Issue by menardorama** [shirou/gopsutil#157]
Hi
Is it possible to implement the run and block queue stored in the /proc/systat ?

It's helpfull to get an overall view on how the system handle the load.

Thanks

**Comment by shirou** [comment]
you mean,  `procs_blocked` and `procs_running` in `/proc/stat` ? From my understanding, this is the number of running and blocked processes.

So you can get these values from this kind of code.
```
func main() {
	procs, err := process.Pids()
	if err != nil {
		return
	}
	var running, blocked int

	for _, p := range procs {
		pp, err := process.NewProcess(p)
		if err != nil {
			continue
		}
		v, err := pp.Status()
		if err != nil {
			continue
		}
		if v == "running" {
			running += 1
		} else if v == "disk sleep" { // sorry, this state name is uncertain
			blocked += 1
		}
	}
	fmt.Println(running)
	fmt.Println(blocked)
}
```

It's not so long. But yes, little bit annoying, because this invokes many `ps` on darwin/freebsd.
So, if you give me a good name, I will implement. I want a purpose-describing name. `host.ProcessState` , or `load.ProcessState`? What do you think?

**Comment by menardorama** [comment]
Hi
Thanks for your feedback, sad to hear that on BSDs it's not implemented....

I thnk that it's related to the load of the system, so saying load.ProcessState is a good option.

Thanks again

**Comment by menardorama** [comment]
And by the way if you can add also the context switching (ctx row in the /proc/stat) it would be awsome !!!

**Comment by shirou** [comment]
@menardorama I implemented procs running/blocked and on `load/add_misc` branch. Could you check it out?
And, currently the name is `Misc`. Because procs and ctx are different so I am very worried about name. I know this is too bad name, so could you give me more applicable name?

**Comment by shirou** [comment]
I have merged with `Misc`. If you think up better name, please re-open this issue and I will change the name. Thank you for your suggestion!
