### ISSUE TITLE
Tests fail with Swedish locale

### ISSUE THREAD

**Issue by walles** [shirou/gopsutil#159]
On my OS X system I get this when running the unit tests:
```
--- FAIL: TestLoad (0.01s)
	load_test.go:11: error strconv.ParseFloat: parsing "3,56": invalid syntax
FAIL
FAIL	github.com/shirou/gopsutil/load	0.053s
--- FAIL: TestSwap_memory (0.01s)
	mem_test.go:22: error strconv.ParseFloat: parsing "1024,00": invalid syntax
FAIL
FAIL	github.com/shirou/gopsutil/mem	0.047s
```

I suspect this is because I'm on a Swedish locale, and that the number formatting rules are different from English:
* English number: `47,123.00`
* Swedish number: `47 123,00` (note ` ` and `,` rather than `,` and `.`)

Could you add a Swedish unit test run to the CI tests?

  Regards /Johan

**Comment by shirou** [comment]
Thank you for reporting. I added `os.Setenv("LC_ALL", "C")` at 3166d415382aa5bbd8bb151cc50a756730cd5ec4. Could you test on latest commit?

> Could you add a Swedish unit test run to the CI tests?

Unfortunately, CI can not test darwin because the CI server is linux. CI just check build-able or not on other platform. And gopsutil read `/prpc` filesystem on Linux, this kind of problem does not occured I think.

**Comment by walles** [comment]
I thought this would fail on Linux as well (you are using `lsof` and possibly others after all), but you're right, it doesn't.

I just tried on Linux with `LANG=sv__SE.UTF-8` and it passed.

Sorry for the noise!
