### ISSUE TITLE
Need clarification on dependency(vendor) package management.

### ISSUE THREAD

**Issue by continuum-milind-adpaiker** [shirou/gopsutil#368]
We are planning to use gopsutil in our project. But it is not very clear how dependency package management is taken care of in gopsutil. 
Can you address below concerns:

1. Which thirdparty packages is gopsutil dependent on and which versions of these dependent packages are to be used? According to our review, we have found that following packages are required for GoPsUtil: 

- 	github.com/shirou/w32
- 	github.com/StackExchange/wmi
- 	github.com/davecgh/go-spew
- 	github.com/pmezard/go-difflib
- 	github.com/stretchr/testify

2. How is dependency managed in gopsutil? Do you use any tool like dep, glide etc. ? Or is it manual?

3. If manual, can you share some information about versions of thirparty packages used?

**Comment by shirou** [comment]
gopsutil itself depends on only these libraries

- github.com/shirou/w32
- github.com/StackExchange/wmi
- github.com/stretchr/testify

`testify` is only for testing. Since `shirou/w32` is managed by me, nothing problem.
So, only `github.com/StackExchange/wmi` may becomes problem.

`StackExchange/wmi` and dependent library `github.com/go-ole/go-ole` is not so change often, the latest version is not problem (at least until now).

gopsutil is a library, so I think fixing version is user's responsibility.

**Comment by continuum-milind-adpaiker** [comment]
Thanks for quick response.
We use glide for dependency management in our projects and planning to use the same if we create a fork of gopsutil. 
Our only worry is since your repository is not using glide (or any other dependency management tool) it can pose problem when we create a pull request on your repo. (since we may end up using different versions of a third party library).

Is it possible you accept our pull request with glide dependency management files in it? This will help to avoid version mismtach problems and manually managing them at the time pull requests.

**Comment by sean-** [comment]
I've dealt with this problem a few times now.  Having libraries vendor their required libraries is problematic.  Ideally `shirou/gopsutil` would publish a SHA1 of the versions that are known to work, but the management of `gopsutil`'s vendored libraries would be punted to the consumer of `gopsuitl` (i.e. it's a bug to have `shirou/gopsutil` include a copy of its necessary dependencies).  I can get into detail more if there are questions re: why.  My rules of thumb re: vendoring is:

* applications/binaries should vendor their libraries
* libraries can have external dependencies on libraries but should not add any packages to `vendor/` in order to prevent conflicts with applications that may include conflicting libraries (e.g. `github.com/StackExchange/wmi`).

**Comment by shirou** [comment]
`glide.yml` and `glide.lock` is same as `gemspec` and `Gemfile.lock` 

- Gemfile : includes dependency
- Gemfile.lock : includes the version of dependent gems

And describes in bellow, `Gemfile.lock is for apps, not libraries`. 

- https://depfu.io/blog/2017/01/18/bundler-and-gemfile-best-practices
- http://yehudakatz.com/2010/12/16/clarifying-the-roles-of-the-gemspec-and-gemfile/

Golang and glide can be resolve dependencies itself, so Gemfile is not required in a library.

That's why I don't include dependency management system in this library.

**Comment by shirou** [comment]
I close this issue. If you have some other reason, please re-open.
