### ISSUE TITLE
Propper usage of CPUPercent()

### ISSUE THREAD

**Issue by mwf** [shirou/gopsutil#44]
Hi! 

cpu.CPUPercent() works very strange on consequent calls - it returns zero CPU usage almost on every call.

Some code:
```
package main

import (
	"fmt"
	psutil "github.com/shirou/gopsutil/cpu"
	"syscall"
	"time"
)

func main() {
	for i := 0; i < 10; i++ {
		cpu_res, e := psutil.CPUPercent(0, false)
		if e == nil {
			fmt.Printf("%d cpu: %v\n", i, cpu_res)
		} else {
			fmt.Printf("Error getting cpu usage: %s\n", e.Error())
			syscall.Exit(1)
		}
		time.Sleep(200 * time.Millisecond)
	}
}
```
Results:
```
0 cpu: [0]
1 cpu: [0.152439024712165]
2 cpu: [0]
3 cpu: [0]
4 cpu: [0]
5 cpu: [0]
6 cpu: [0]
7 cpu: [0]
8 cpu: [0]
9 cpu: [0]
```
What am I doing wrong?
OS Debian Wheezy

**Comment by shirou** [comment]
200 msec is a little bit short to get CPUPercent. Please try to set 1sec.
I confirmed on Debian 7.0 x64 using original psutil (https://github.com/giampaolo/psutil) and set 1sec, not 200msec.

And, the first argument of CPUPercent is duration to wait. You can just write like this in order to wait specific time.
```go
cpu_res, e := psutil.CPUPercent(time.Duration(1) * time.Second, false)
```
if duration is 0, it use difference from previous call.

**Comment by shirou** [comment]
I close this issue. feel free to reopen. Thank you.

**Comment by mwf** [comment]
Thanks, I'll try it out!
