### ISSUE TITLE
Issue with getting Process information on OSX

### ISSUE THREAD

**Issue by cjbassi** [shirou/gopsutil#513]
I'm fetching all of the running processes and then retrieving the Pid, Name(), CPUPercent(), and MemoryPercent() of each which is very slow on OSX, but not Linux. Takes at least 30 seconds for all the processes. When getting this info asynchronously using goroutines, it's much faster but uses 100% CPU.

Issue happens on macOS 10.13.3, macos 10.12.6.

Relevant code [here](https://github.com/cjbassi/gotop/blob/7d0abdad08b0fa606f64b325a8a21d7d38e5ac84/widgets/proc.go#L81).

**Comment by shirou** [comment]
on Darwin, we use ps command to get processes information ([code](https://github.com/shirou/gopsutil/blob/master/process/process_darwin.go#L612)). This requires much more CPUs rather than Linux. 

perhaps, we can use [syscall](https://github.com/shirou/gopsutil/blob/master/process/process_darwin.go#L529) but I have not a Darwin anymore, so I can not develop. PR is always welcome!

**Comment by f1337** [comment]
It looks like syscall is being used, not ps: https://github.com/shirou/gopsutil/blob/6a368fb7cd1221fa6ea90facc9447c9a2234c255/process/process_darwin.go#L533

Am I reading this incorrectly?
