### ISSUE TITLE
Question: Are there alternatives to this library?

### ISSUE THREAD

**Issue by lrtanner** [shirou/gopsutil#548]
My system unfortunately has an overloaded WMI process and querying for stats with this library causes major performance issues. Is there a good alternative to gopsutil?

**Comment by shirou** [comment]
Could you ask on StackOvwrflow?

**Comment by lrtanner** [comment]
StackOverflow does not allow questions seeking specific library recommendations. I did ask on there and was downvoted and had my question closed. Not sure what to do from here.

**Comment by Lomanic** [comment]
Help to remove the awfully slow wmi calls is always appreciated. Otherwise, can you tell us what functions from the lib you are using to gather stats, so we might maybe prioritize our efforts on these ones?

See also [golang.org/help](https://golang.org/help/) for other channels than StackOverflow, but I don't know of any alternative to gopsutil. Maybe you could reuse python psutil C code with cgo but I'm not even sure and I won't be of any help.
