### ISSUE TITLE
use of unguarded globals in disk_darwin.h can crash process under high concurrency

### ISSUE THREAD

**Issue by vilterp** [shirou/gopsutil#560]
### Repro

On mac, call `disk.IOCountersWithContext` concurrently from many goroutines.

### Expected

Everything is fine.

### Actual

Can crash with a pretty gnarly error, like this: https://github.com/cockroachdb/cockroach/issues/27867

### Diagnosis

The functions in `disk_darwin.h` use mutable global variables that aren't guarded by a mutex: https://github.com/shirou/gopsutil/blob/master/disk/disk_darwin.h#L34-L39

### Remedy

Put some kind of a mutex around those globals or do without the globals. This [lufia/iostat](https://github.com/lufia/iostat) seems to provide the same stats without using globals: https://github.com/lufia/iostat/blob/master/iostat_darwin.c

We are temporarily switching to that library for darwin only, but would like to only have to use this library, since it provides so much other useful stuff. (Thanks!)

**Comment by rburchell** [comment]
heh, indeed, sorry about that. I was very new to cgo at the time, and really wasn't at the stage for thinking about things like concurrency there :)..

i'd offer to help, but similar to shirou, I don't use macos anymore. if it was me doing it, i'd change StartIOCounterFetch to take a pointer to a struct to store state in rather than using globals for them.

**Comment by vilterp** [comment]
W00t, thanks @Lomanic and @shirou!
