### ISSUE TITLE
Determine if process is running in the foreground

### ISSUE THREAD

**Issue by tab1293** [shirou/gopsutil#596]
Is there any way to determine if a process loaded with `process.NewProcess(<pid>)` is running in the foreground? 

I am looking for similar functionality to what `ps -O -p <pid>` returns in the `STAT` column; if there is a `+` in that column then the process is running in the foreground.

**Comment by Lomanic** [comment]
This is not possible with gopsutil currently (python psutil doesn't seem to support that either).

If we implement a `process.Background()` function, we will probably return a [ErrNotImplementedError](https://github.com/shirou/gopsutil/blob/a11c78ba2c13c5b1ee59c53296ba35f92f0ce658/internal/common/common.go#L95) (or a new  `errors.New("not implemented on Windows")`) on Windows which doesn't have this concept at all.

**Comment by shirou** [comment]
gopsutil uses only a first chars on `/proc/<pid>/status` in linux. So other information like foreground/session leader is discarded. 

This is because these status is very different on each platforms, like @Lomanic said. If you make a PR which can abstract these differences, we will merge it with many thanks.

**Comment by Lomanic** [comment]
From my research:

* getting foreground status with `ps` is as simple as checking if the result of `ps -o stat= -p $PID` has a `+` (useful for darwin and BSDs which don't have a procfs)
* GNU procps' ps (and in darwin's [adv_cmds](https://opensource.apple.com/tarballs/adv_cmds/) in `ps/print.c`) implements the `+` state [by comparing tpgid and pgrp](https://salsa.debian.org/debian/procps/blob/dde21be6e4a17ccd51382cc6f222fe8fac9887b4/ps/output.c), which are available on Linux in `/proc/$PID/stat` at field 5 (pgrp) and 8 (tpgid ; see procfs' manpage).

I plan to implement this in the coming weeks if nobody does this in the mean time.

**Comment by shirou** [comment]
Thank you for researching @Lomanic .

I think adding a field to `Process` struct, something like `string []substate` is better. but if you have any other idea.

And, we can also define const instead of string.
```
const (
     SubStateSessionLeader = "session leader"
     SubStateForeground = "foreground"
)
```

**Comment by Lomanic** [comment]
Indeed, the change you are suggesting (changing `process.State()` to return `[]string, err`), that I agree with, will be a breaking change for the API (v3 then). I also find it better to use exported constants, for users to compare with, instead of [just letters](https://godoc.org/github.com/shirou/gopsutil/process#Process.Status). It would reflect `ps` `STAT` column.

**Comment by shirou** [comment]
> the change you are suggesting (changing process.State() to return []string, err)

Ah, you are right. forget about my previous comment. Then, `process.Background() (bool, err)` seems good for me.

>  I also find it better to use exported constants, ...(snip)

That's a good idea!

**Comment by Lomanic** [comment]
I added the API change to `process.State` to the v3 roadmap at #362, I think this should be implemented as it would reflect `ps` and would simplify the API (instead of having multiple functions, for each sub-state), plus it would read once the result of `ps` or `/proc/$PID/stat(us)` for better performance.

**Comment by DesignofIntelligence** [comment]
> Is there any way to determine if a process loaded with `process.NewProcess(<pid>)` is running in the foreground?
> 
> I am looking for similar functionality to what `ps -O -p <pid>` returns in the `STAT` column; if there is a `+` in that column then the process is running in the foreground.

Here's one way to do it
`cmd = 'powershell "gps | where {$_.MainWindowTitle } | select ProcessName'  # ,Description,Id,Path'
    processes = subprocess.Popen(cmd, shell=True, stdout=subprocess.PIPE)
    for line in processes.stdout:
        if line.rstrip():  # line is not empty
            process = line.decode().rstrip()`
