### ISSUE TITLE
Calling mem.SwapMemory() results in `xswdev version mismatch` error in FreeBSD 12

### ISSUE THREAD

**Issue by danielnelson** [shirou/gopsutil#635]
**Describe the bug**

Calling `mem.SwapMemory()` results in `xswdev version mismatch` error in FreeBSD 12.

**To Reproduce**

```go
package main

import (
	"fmt"

	"github.com/shirou/gopsutil/mem"
)

func main() {
	res, err := mem.SwapMemory()
	if err != nil {
		fmt.Println(err)
		return
	} else {
		fmt.Println(res)
	}
}
```

**Expected behavior**

SwapMemory stats are returned and error is nil.

**Environment (please complete the following information):**

```
> freebsd-version -k -r -u
12.0-STABLE
12.0-STABLE
12.0-STABLE
> uname -a
FreeBSD dev 12.0-STABLE FreeBSD 12.0-STABLE r343685 DL360  amd64
```

**Additional context**

https://github.com/influxdata/telegraf/issues/5395

**Comment by shirou** [comment]
This is because `XSWDEV_VERSION` is updated to `2` https://github.com/freebsd/freebsd/blob/master/sys/vm/vm_param.h#L95

[this commit](https://github.com/freebsd/freebsd/commit/e75ba1d5c4c79376a78351c8544388491db49664) changes this and in this commit, 

it seems `struct xswdev` is  changed.

- xswdev https://github.com/freebsd/freebsd/blob/1d6e4247415d264485ee94b59fdbc12e0c566fd0/sys/vm/vm_param.h#L95
- xswdev11 https://github.com/freebsd/freebsd/blob/7ee1aa34d4b8c0ffe1dca7eb9f0eaf8491e56c64/sys/vm/swap_pager.c#L2470

The difference is `dev_t` and from [here](https://github.com/freebsd/freebsd/blob/1d6e4247415d264485ee94b59fdbc12e0c566fd0/sys/sys/_types.h#L112), dev_t is uint64.
 
I opened #636 but not tested yet on FreeBSD12 since I have not 12 yet... I will appreciate if you can check the PR before I prepare a machine.

**Comment by nbari** [comment]
I created some [images](https://fabrik.red/post/test/) for FreeBSD12 (https://github.com/fabrik-red/images/releases/tag/12.0) , the image works out of the box in some [cloud provider](https://fabrik.red/post/aws-ami/)s or locally using  virtualbox/vmware  fusion, if need help adding some options please let me know, the latest one I tested is: https://github.com/fabrik-red/images/releases/download/12.0/disk-zfs-swap.tar.gz (using swap on zfs only)

**Comment by nbari** [comment]
Hi @shirou, just tested using ` FreeBSD 12.0-STABLE r343736 ` and seems to be working, this is the code I used:

```go
package main

import (
        "fmt"

        "github.com/shirou/gopsutil/mem"
)

func main() {
        res, err := mem.SwapMemory()
        if err != nil {
                fmt.Println(err)
                return
        }
        fmt.Println(res)
}
```

This is the output:
    
    {"total":1073741824,"used":395075584,"free":678666240,"usedPercent":36.794281005859375,"sin":0,"sout":0}



```
# swapinfo -h
Device          1K-blocks     Used    Avail Capacity
/dev/zvol/zroot/swap   1048576     377M     647M    37%
```

**Comment by shirou** [comment]
Thank you for joining the suggestion and confirmation. I merged the PR and I think it works well now.
