### ISSUE TITLE
disk.IOCounters() get wrong "readTime","writeTime" on windows 10

### ISSUE THREAD

**Issue by superscari** [shirou/gopsutil#866]
I download 40G+ data into my H: zone in win10 PC, during more than 2 hours.  But the output of `disk.IOCounters()` method  is as belows:
"readTime":3980,"writeTime":6120,"iopsInProgress":0,"ioTime":0,"weightedIO":0,"name":"H:"
i think the *TIme got are all wrong. 
Is that a bug?

**Comment by Lomanic** [comment]
We are returning the same values on Windows as psutil's [disk_io_counters function](https://psutil.readthedocs.io/en/latest/#psutil.disk_io_counters) since #850. Your numbers can be explained by the fact that data was not constantly written to disk (throttled by network mainly, but I think even a local copy cold be interrupted by OS multi-tasking).

**Comment by superscari** [comment]
new problem, in one of my two windows server2008 R2,  the readtime is 
![5F5C72BF-1DE8-4f09-81CD-4251EE2945C3](https://user-images.githubusercontent.com/16182046/82209107-4eaa6280-993f-11ea-8559-d89ee342ceed.png)
，but in another pc , it works well
